### ISSUE TITLE
Support IP2Proxy API in rIP?

### ISSUE THREAD

**Issue by topa202020** [MAHDLab/rIP#10]
Do you plan to support the [IP2Proxy API](https://www.ip2location.com/web-service/ip2proxy) in the library?

We would like to use it to detect residential proxy which is not available in other API at this moment.

**Comment by pdwaggoner** [comment]
Hi @topa202020 - thanks for the suggestion! At the moment, we don't have plans to add support for this service, as there doesn't appear to be a free entry point. That said, we are open to [pull requests](https://github.com/MAHDLab/rIP/pulls) with feature suggestions if you'd care to contribute ideas. You can work shop these in this (or another) issue ticket as well.
