### ISSUE TITLE
Issue with ipintel_key

### ISSUE THREAD

**Issue by pdwaggoner** [MAHDLab/rIP#11]
Ping @hrbrmstr - getting this issue only with `ipintel_key()`:

```{r}
Error in `[.data.frame`(x, r, vars, drop = drop) : 
  undefined columns selected
```

I can't locate it, but suspect it may be an issue with a change on the IP Intel side of things? Any wisdom would be welcomed, as I continue checking. Thanks!

**Comment by SantosLuiza** [comment]
Hi, thanks for putting this together. I am also getting the same issue with getIPinfo() using iphub_key, both with my own code and with the sample code provided in the README file.

**Comment by SantosLuiza** [comment]
Quick update: If I use a free IP Hub Key the code works, the error message only happens when I used an upgraded IP Hub Key (the one that allows for 10k IPs a day).

**Comment by pdwaggoner** [comment]
Thanks for the note and for letting us know. To ensure widest access, we have written the code to work only with free services, given limited resources of many users of the package (i.e., the inability for many to upgrade to paid services). This is the reason for the error you encountered. Sorry to hear of this! We are currently considering how/whether to allow for paid entry points as well, but there is nuance to this update to the function. I will add the `enhancement` label, and mark this as closed given the lack of current support.

**Comment by pdwaggoner** [comment]
For my benefit, can you share the error message you're getting? Thanks!
