### ISSUE TITLE
STRSXP error

### ISSUE THREAD

**Issue by bshor** [MAHDLab/rIP#7]
Hi everyone,

I'm getting an error with getIPinfo() using IPHub. Here's what it looks like:

```
z <- getIPinfo(d=ubi.out, "ipaddress",iphub_key = "xxx")

Error in iptools::ip_classify(ips[i]) :
  Not compatible with STRSXP: [type=list].
```

My API key totally worked in the Shiny app with several hundred observations. Now I'm in the several thousand so I wanted to use the R package.

Any ideas?

**Comment by bshor** [comment]
I figured out the cause: the error indicates the input is a tibble (automatically produced by dplyr) rather than a base R data frame. The user solution is just to transform the tibble to a data frame, then everything works.

**Comment by pdwaggoner** [comment]
Thanks Boris!
