### ISSUE TITLE
rIP dropping observations?

### ISSUE THREAD

**Issue by hannah-solheim** [MAHDLab/rIP#9]
I'm attempting to use rIP's getIPinfo function. I'm passing in a dataframe with 80 different IP addresses. However, when I run the code, rIP produces a data frame with only 17 rows (i.e. the data corresponding to 63 IP addresses is not recorded). Is this because of request limits on IP Hub, or one of the other services?

**Comment by pdwaggoner** [comment]
Hi @hannah-solheim - Thanks for using the package. Can you provide a reproducible example here in the issue thread for me to debug? If using real data that is more sensitive, feel free to email me directly (pdwaggoner@uchicago.edu). Thanks!
